### ISSUE TITLE
Nightly Linux packaging tests failing (CycloneDDS test)

### ISSUE THREAD

**Issue by emersonknapp** [ros2/ros1_bridge#239] opened 2020-02-06 21:59 UTC
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 18.04
- Installation type:
  - Source
- Version or commit hash:
  - Latest
- DDS implementation:
  - CycloneDDS
- Client library (if applicable):
  - N/A

#### Steps to reproduce issue

CycloneDDS tests are failing in this package on all Ubuntu nightly packaging builds
https://ci.ros2.org/view/packaging/job/packaging_linux-aarch64/1094/testReport/
https://ci.ros2.org/view/packaging/job/packaging_linux-armhf/329/testReport/
https://ci.ros2.org/view/packaging/job/packaging_linux/1748/testReport/

This seems to have been failing for 3 months (or something has been) - last stable build reported 3mo 21 days ago.

#### Expected behavior

Builds are green

#### Actual behavior

Builds are yellow

**Comment by dirk-thomas** [comment] 2020-02-06 23:36
Duplicate of ros2/rmw_cyclonedds#72.

**Closed by dirk-thomas** 2020-02-06 23:36 UTC
Labels: duplicate
