### ISSUE TITLE
terminate called after throwing an instance of 'std::runtime_error'

### ISSUE THREAD

**Issue by shengwen1997** [ros2/ros1_bridge#30] opened 2016-09-10 15:53 UTC
Hello,

I am now testing the ros1_bridge, I compiled the project by myself.

However, after I type the command "ros1_bridge_listener"  the following message just shows up:

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  could not create subscription: type support implementation 'introspection_cpp'(0x7fcbc1e2d669) does not match rmw implementation 'opensplice_static'(0x7fcbc04b4659), at /home/shengwen-asus/ros2_ws/src/ros2/rmw_opensplice/rmw_opensplice_cpp/src/rmw_subscription.cpp:66, at /home/shengwen-asus/ros2_ws/src/ros2/rcl/rcl/src/rcl/subscription.c:76
Aborted
```

Environment:

* ROS2 alpha7

* Ubuntu 16.04 (x64) 

Could you guys give me any help?

**Comment by dirk-thomas** [comment] 2016-09-10 21:56
The error message says that the type support is not the right one to be used with OpenSplice. Can you please provide more information how you built it, what rmw implementation you installed (OpenSplice I assume), and if the problem still happens if you do a clean rebuild of the workspace (delete build and install spaces and build again).

**Comment by shengwen1997** [comment] 2016-09-12 07:36
I tried the prebuild version and my own compiled version, both will report the same message.

My DDS implementation is "OpenSlpice", and I installed the implementation by typing the following command:

```
sudo apt install libopensplice64
``` 

thanks

**Comment by dirk-thomas** [comment] 2016-09-14 20:47
I can confirm the problem for the `ros1_bridge_talker` and `ros1_bridge_listener` for the packages binaries using OpenSplice.

**Comment by dirk-thomas** [comment] 2016-09-14 21:09
A local build as well as the nightly package seem to work fine for me. Can you please try the latest nightly package (http://ci.ros2.org/view/packaging/job/packaging_linux/383/) and comment if that works for you.

**Comment by dirk-thomas** [comment] 2016-09-14 21:17
Closing as duplicate of #30. The fix has landed after the alpha 7 tags. That's why the released binaries don't work.

**Closed by dirk-thomas** 2016-09-14 21:17 UTC
Labels: bug

**Comment by dhood** [comment] 2016-09-14 21:21
@dirk-thomas would have meant to refer to #29

**Comment by shengwen1997** [comment] 2016-09-15 08:43
Thanks, I will try this again and report to you guys

**Comment by shengwen1997** [comment] 2016-09-15 10:32
The prebuild version work fine now, but the one I compiled from source failed.
Where can I get the newest source code?  my source code was generate by **vcs** command

**Comment by dirk-thomas** [comment] 2016-09-15 14:38
I assume you have cloned the repositories using the `ros2.repos` file. The tutorial recommends to download that file from the latest release tag. As an alternative you could get the latest version of that file from the master branch.

A simpler approach could be to only switch your already cloned repository of `ros1_bridge` to the master branch and update to the current state. I haven't tried that combination myself though.

**Comment by dhood** [comment] 2016-09-15 18:35
@shengwen1997 You may find https://github.com/ros2/ros2/wiki/Maintaining-a-Source-Checkout-in-Linux-or-OS-X#development-branches useful for updating to the newest source code.

**Comment by shengwen1997** [comment] 2016-09-17 04:32
I git pull the latest commit at master branch and everything works perfect now, thanks for helping!
